version: '3.9'

services:
  java_app:
    container_name: java_app
    image: challenge-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - url=jdbc:postgresql://java_db:5432/postgres
      - username=postgres
      - password=123456
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
        - 5432:5432
